print("Hello to Awwab's Madlib!\nTo start enter your name: ")
na = input()
print("\nNow a verb: ")
v = input()
print("\nNow an adjective: ")
a = input()
print("\nNow another noun: ")
n = input()
print(na, " ", v, " the ", n," ", a)